version: '3.10'
services:
  backend:
    build: .
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - .env
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - db_network
    volumes:
      - .:/Forex
  postgres-db:
    ports:
      - '5433:5432'
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - db_network

volumes:
  postgres-data:

networks:
  db_network:
    driver: bridge