# Generated by Django 5.0.2 on 2024-02-17 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_options_alter_lecture_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="rating",
        ),
    ]
