# Generated by Django 5.0.2 on 2024-02-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_courseimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.FileField(upload_to="courses/images/", verbose_name="Image"),
        ),
        migrations.DeleteModel(
            name="CourseImages",
        ),
    ]
