# Generated by Django 5.0.2 on 2024-02-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_course_image_delete_courseimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(upload_to="courses/images/", verbose_name="Image"),
        ),
    ]
