# Generated by Django 5.0.2 on 2024-02-17 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="video_url",
            field=models.URLField(
                default=django.utils.timezone.now, verbose_name="Ссылка на видео"
            ),
            preserve_default=False,
        ),
    ]
