# Generated by Django 5.0.2 on 2024-02-17 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_lecture_video_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("course", "user")},
        ),
    ]
