# Generated by Django 5.0.2 on 2024-02-29 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="video_file",
            field=models.FileField(
                help_text="Supported formats: mp4, mov, avi, webm, mkv, flv, wmv, m4v, mpeg, 3gp",
                upload_to="lectures/video/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "mov",
                            "avi",
                            "webm",
                            "mkv",
                            "flv",
                            "wmv",
                            "m4v",
                            "mpeg",
                            "3gp",
                        ]
                    )
                ],
                verbose_name="Video File",
            ),
        ),
    ]
