# Generated by Django 5.0.2 on 2024-02-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "★"), (2, "★★"), (3, "★★★"), (4, "★★★★"), (5, "★★★★★")],
                verbose_name="Рейтинг",
            ),
        ),
    ]
