# Generated by Django 5.0.2 on 2024-02-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Эмайл'),
            preserve_default=False,
        ),
    ]
